#!/bin/bash

# Change working diretory to the scripts directory
cd /Users/jarp/Dropbox/Personal/WARP\ Worldwide/WARP\ Source/JWeb/SQL/DbBuild


# Call mysql from the command line, redirect STDIN to the script file for input. 
# -u is user -p is password.
mysql -u root -p62XYhC\;erw\;zZaCmZVzrFEwW < 01_WarpAdmin2017.sql

# Change working directory to the StoredProcedures directory
cd /Users/jarp/Dropbox/Personal/WARP\ Worldwide/WARP\ Source/JWeb/SQL/StoredProcedures

# echo SP_registerUserAccount
# mysql -u root -p62XYhC\;erw\;zZaCmZVzrFEwW < SP_registerUserAccount.sql

echo "Starting Stored Procedure Creation. "

 for file in {.*,SP_*}; 
 do 
 	echo "$file";
 	mysql -u root -p62XYhC\;erw\;zZaCmZVzrFEwW < $file;
 done
 	
 	
echo "Stored Procedure Creation Complete."
 	